#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# ///
"""Overlay every upstream string that names Nagram with SereinGram's name.

Nagram's translations come from its Crowdin project and are merged from
upstream, so they are not edited in place. Each string whose value names
Nagram is written, renamed, to TMessagesProj/src/serein/res, which every build
type merges over src/main/res. Rerun after merging upstream translations.

Run from the repository root:
    uv run Tools/serein/brand/generate_strings.py
"""

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
UPSTREAM = ROOT / "TMessagesProj/src/main/res"
OVERLAY = ROOT / "TMessagesProj/src/serein/res"
OUTPUT = "strings_brand.xml"
# SereinGram's own text names Nagram on purpose, as the project it is based on.
OWN_STRINGS = "strings_serein"
UPSTREAM_NAME = re.compile("Nagram")
APP_NAME = "SereinGram"
STRING = re.compile(r'<string\s+name="([^"]+)"([^>]*)>(.*?)</string>', re.DOTALL)
STRING_TAG = re.compile(r"<string[\s>/]")
GENERATED = "<!-- Generated by Tools/serein/brand/generate_strings.py. -->"


def renamed(folder):
    strings = {}
    for path in sorted(folder.glob("strings*.xml")):
        if path.name.startswith(OWN_STRINGS):
            continue
        text = path.read_text(encoding="utf-8")
        found = STRING.findall(text)
        # A string the pattern cannot read, such as an empty <string/>, must not be skipped unseen.
        if len(found) != len(STRING_TAG.findall(text)):
            sys.exit(f"{path}: some <string> elements do not have the form this script reads")
        for name, attributes, value in found:
            if UPSTREAM_NAME.search(value):
                strings[name] = (attributes, UPSTREAM_NAME.sub(APP_NAME, value))
    return strings


def main():
    for stale in OVERLAY.glob(f"values*/{OUTPUT}"):
        if not (UPSTREAM / stale.parent.name).is_dir():
            stale.unlink()
    for folder in sorted(UPSTREAM.glob("values*")):
        target = OVERLAY / folder.name / OUTPUT
        strings = renamed(folder)
        if not strings:
            target.unlink(missing_ok=True)
            continue
        lines = [
            f'    <string name="{name}"{attributes}>{value}</string>\n'
            for name, (attributes, value) in sorted(strings.items())
        ]
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(
            '<?xml version="1.0" encoding="utf-8"?>\n'
            f"{GENERATED}\n"
            "<resources>\n"
            f"{''.join(lines)}"
            "</resources>\n",
            encoding="utf-8",
        )


if __name__ == "__main__":
    main()
