#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "fonttools==4.66.1",
#     "pillow==12.3.0",
#     "resvg-py==0.5.0",
#     "uharfbuzz==0.56.3",
# ]
# ///
"""Generate the SereinGram Android icons from the master logo.

The logo was designed by OukaroMF (https://github.com/OukaroMF/). Its master
file, Tools/serein/brand/sereingram-logo.svg, is kept exactly as delivered and
is the same file the desktop client ships. Application icons place it on a
light tile; the monochrome glyphs reuse its dark paths and leave the lighter
folds open, as on desktop. The wordmark is the application name set in the
Roboto Medium the app already bundles for its titles.

Run from the repository root:
    uv run Tools/serein/brand/generate_icons.py
"""

import io
import xml.etree.ElementTree as ET
from pathlib import Path

import resvg_py
import uharfbuzz
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from PIL import Image, ImageDraw

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
MAIN = ROOT / "TMessagesProj/src/main"
RES = MAIN / "res"
MASTER = HERE / "sereingram-logo.svg"
TITLE_FONT = MAIN / "assets/fonts/rmedium.ttf"
APP_NAME = "SereinGram"
# Height of the upstream wordmarks; the box spans cap height to the g descender.
WORDMARK_HEIGHT = 20.408922

SVG_NAMESPACE = "http://www.w3.org/2000/svg"
DARK_FILL = "#09090B"
TILES = {
    "": ((255, 255, 255), (244, 244, 245), (228, 228, 231)),
    "_green": ((240, 253, 244), (220, 252, 231), (187, 247, 208)),
}
DENSITIES = {"mdpi": 1, "hdpi": 1.5, "xhdpi": 2, "xxhdpi": 3, "xxxhdpi": 4}
SUPERSAMPLE = 4
GLYPH_SPAN = 0.74
BORDER = 0.008
ADAPTIVE_CANVAS = 108
ADAPTIVE_VISIBLE = 72
LEGACY_SIZE = 48
LEGACY_MARGIN = 1 / 24
LEGACY_RADIUS = 0.2
NOTIFICATION_SIZE = 24
NOTIFICATION_SPAN = 20 / 24
MENU_SPAN = 18 / 24
STORE_SIZE = 512
GENERATED = "<!-- Generated by Tools/serein/brand/generate_icons.py. -->"

ET.register_namespace("", SVG_NAMESPACE)


def master():
    return ET.fromstring(MASTER.read_text(encoding="utf-8"))


def logo_paths(dark_only=False):
    paths = []
    for element in master():
        fill = element.get("fill", "").upper()
        if dark_only and fill != DARK_FILL:
            continue
        paths.append((element.get("d"), fill))
    return paths


def render_svg(root, size):
    text = ET.tostring(root, encoding="unicode")
    data = resvg_py.svg_to_bytes(svg_string=text, width=size, height=size)
    return Image.open(io.BytesIO(bytes(data))).convert("RGBA")


def glyph_box():
    size = 2048
    root = master()
    bbox = render_svg(root, size).getchannel("A").getbbox()
    scale = float(root.get("viewBox").split()[2]) / size
    return tuple(value * scale for value in bbox)


BOX = glyph_box()


def fit(canvas, span):
    """Scale and offset that center the glyph box in a square canvas."""
    x0, y0, x1, y1 = BOX
    scale = canvas * span / max(x1 - x0, y1 - y0)
    return scale, canvas / 2 - scale * (x0 + x1) / 2, canvas / 2 - scale * (y0 + y1) / 2


def framed(root, size, span):
    x0, y0, x1, y1 = BOX
    side = max(x1 - x0, y1 - y0) / span
    center = ((x0 + x1) / 2, (y0 + y1) / 2)
    root.set(
        "viewBox", f"{center[0] - side / 2:.4f} {center[1] - side / 2:.4f} {side:.4f} {side:.4f}"
    )
    root.set("width", str(size))
    root.set("height", str(size))
    return root


def tile(size, colors, shape, margin, radius):
    big = size * SUPERSAMPLE
    inset = round(big * margin)
    box = (inset, inset, big - inset - 1, big - inset - 1)
    side = big - 2 * inset
    top, bottom, border = colors
    column = Image.new("RGBA", (1, big))
    for y in range(big):
        t = y / max(big - 1, 1)
        rgb = tuple(round(a + (b - a) * t) for a, b in zip(top, bottom, strict=True))
        column.putpixel((0, y), (*rgb, 255))
    fill = column.resize((big, big))
    mask = Image.new("L", (big, big), 0)
    outline = Image.new("RGBA", (big, big), (0, 0, 0, 0))
    width = max(1, round(side * BORDER))
    if shape == "round":
        ImageDraw.Draw(mask).ellipse(box, fill=255)
        ImageDraw.Draw(outline).ellipse(box, outline=(*border, 255), width=width)
    elif radius:
        corner = round(side * radius)
        ImageDraw.Draw(mask).rounded_rectangle(box, radius=corner, fill=255)
        ImageDraw.Draw(outline).rounded_rectangle(
            box, radius=corner, outline=(*border, 255), width=width
        )
    else:
        mask.paste(255, (inset, inset, big - inset, big - inset))
    image = Image.new("RGBA", (big, big), (0, 0, 0, 0))
    image.paste(fill, (0, 0), mask)
    if shape == "round" or radius:
        image.alpha_composite(outline)
    return image.resize((size, size), Image.LANCZOS)


def render(size, colors, shape="square", margin=LEGACY_MARGIN, radius=LEGACY_RADIUS):
    image = tile(size, colors, shape, margin, radius)
    image.alpha_composite(render_svg(framed(master(), size, GLYPH_SPAN * (1 - 2 * margin)), size))
    return image


def hex_color(rgb):
    return "#" + "".join(f"{value:02X}" for value in rgb)


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def vector(size, body, aapt=False):
    namespaces = '    xmlns:aapt="http://schemas.android.com/aapt"\n' if aapt else ""
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f"{GENERATED}\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f"{namespaces}"
        f'    android:width="{size}dp"\n'
        f'    android:height="{size}dp"\n'
        f'    android:viewportWidth="{size}"\n'
        f'    android:viewportHeight="{size}">\n'
        f"{body}"
        "</vector>\n"
    )


def glyph_vector(size, span, dark_only):
    scale, dx, dy = fit(size, span)
    lines = [
        "    <group\n",
        f'        android:scaleX="{scale:.6f}"\n',
        f'        android:scaleY="{scale:.6f}"\n',
        f'        android:translateX="{dx:.4f}"\n',
        f'        android:translateY="{dy:.4f}">\n',
    ]
    for data, fill in logo_paths(dark_only):
        color = "#FFFFFFFF" if dark_only else fill
        lines.append(
            "        <path\n"
            f'            android:fillColor="{color}"\n'
            f'            android:pathData="{data}" />\n'
        )
    lines.append("    </group>\n")
    return vector(size, "".join(lines))


def background_vector(colors, gradient):
    top, bottom, _ = colors
    canvas = ADAPTIVE_CANVAS
    shape = f"M0,0h{canvas}v{canvas}h-{canvas}z"
    if not gradient:
        body = f'    <path\n        android:fillColor="{hex_color(top)}"\n        android:pathData="{shape}" />\n'
        return vector(canvas, body)
    body = (
        f'    <path android:pathData="{shape}">\n'
        '        <aapt:attr name="android:fillColor">\n'
        "            <gradient\n"
        '                android:type="linear"\n'
        f'                android:startX="{canvas / 2:g}"\n'
        '                android:startY="0"\n'
        f'                android:endX="{canvas / 2:g}"\n'
        f'                android:endY="{canvas}"\n'
        f'                android:startColor="{hex_color(top)}"\n'
        f'                android:endColor="{hex_color(bottom)}" />\n'
        "        </aapt:attr>\n"
        "    </path>\n"
    )
    return vector(canvas, body, aapt=True)


def wordmark_vector():
    font = TTFont(TITLE_FONT)
    glyphs = font.getGlyphSet()
    order = font.getGlyphOrder()
    shaper = uharfbuzz.Font(uharfbuzz.Face(uharfbuzz.Blob.from_file_path(str(TITLE_FONT))))
    buffer = uharfbuzz.Buffer()
    buffer.add_str(APP_NAME)
    buffer.guess_segment_properties()
    uharfbuzz.shape(shaper, buffer, {"kern": True, "liga": True})
    outline = SVGPathPen(glyphs, ntos=lambda value: f"{value:g}")
    ink = BoundsPen(glyphs)
    advance = 0
    for info, position in zip(buffer.glyph_infos, buffer.glyph_positions, strict=True):
        offset = (1, 0, 0, -1, advance + position.x_offset, -position.y_offset)
        for pen in (outline, ink):
            glyphs[order[info.codepoint]].draw(TransformPen(pen, offset))
        advance += position.x_advance
    descender = BoundsPen(glyphs)
    glyphs["g"].draw(TransformPen(descender, (1, 0, 0, -1, 0, 0)))
    x0, y0, x1, _ = ink.bounds
    y1 = descender.bounds[3]
    width_dp = WORDMARK_HEIGHT * (x1 - x0) / (y1 - y0)
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f"{GENERATED}\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{width_dp:.4f}dp"\n'
        f'    android:height="{WORDMARK_HEIGHT}dp"\n'
        f'    android:viewportWidth="{x1 - x0:g}"\n'
        f'    android:viewportHeight="{y1 - y0:g}">\n'
        "    <group\n"
        f'        android:translateX="{-x0:g}"\n'
        f'        android:translateY="{-y0:g}">\n'
        "        <path\n"
        '            android:fillColor="#FFFFFFFF"\n'
        f'            android:pathData="{outline.getCommands()}" />\n'
        "    </group>\n"
        "</vector>\n"
    )


def adaptive_icon(suffix):
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f"{GENERATED}\n"
        '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        f'    <background android:drawable="@drawable/ic_launcher{suffix}_background" />\n'
        '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
        '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n'
        "</adaptive-icon>\n"
    )


def main():
    span = GLYPH_SPAN * ADAPTIVE_VISIBLE / ADAPTIVE_CANVAS
    write(RES / "drawable/ic_launcher_foreground.xml", glyph_vector(ADAPTIVE_CANVAS, span, False))
    write(RES / "drawable/ic_launcher_monochrome.xml", glyph_vector(ADAPTIVE_CANVAS, span, True))
    write(
        RES / "drawable/serein_notification.xml",
        glyph_vector(NOTIFICATION_SIZE, NOTIFICATION_SPAN, True),
    )
    write(RES / "drawable/serein_menu.xml", glyph_vector(NOTIFICATION_SIZE, MENU_SPAN, True))
    for suffix, colors in TILES.items():
        name = f"ic_launcher{suffix}_background.xml"
        write(RES / "drawable" / name, background_vector(colors, gradient=False))
        write(RES / "drawable-v24" / name, background_vector(colors, gradient=True))
        for round_suffix in ("", "_round"):
            write(
                RES / f"mipmap-anydpi-v26/ic_launcher{suffix}{round_suffix}.xml",
                adaptive_icon(suffix),
            )
        for density, factor in DENSITIES.items():
            size = round(LEGACY_SIZE * factor)
            folder = RES / f"mipmap-{density}"
            folder.mkdir(parents=True, exist_ok=True)
            render(size, colors).save(folder / f"ic_launcher{suffix}.png", optimize=True)
            render(size, colors, shape="round").save(
                folder / f"ic_launcher{suffix}_round.png", optimize=True
            )
    for density, factor in DENSITIES.items():
        size = round(LEGACY_SIZE * factor)
        folder = RES / f"drawable-{density}"
        folder.mkdir(parents=True, exist_ok=True)
        render(size, TILES[""], shape="round", margin=0).save(
            folder / "ic_launcher_dr.png", optimize=True
        )
    store = render(STORE_SIZE, TILES[""], margin=0, radius=0)
    store.save(MAIN / "ic_launcher-playstore.png", optimize=True)
    store.save(MAIN / "ic_launcher_web.png", optimize=True)
    write(RES / "drawable/serein_wordmark.xml", wordmark_vector())


if __name__ == "__main__":
    main()
